### PR TITLE
Change IOC reserved1/2 subformat to 'H2', which forces afp writer to output \x00.

### PR DESCRIPTION
**Pull request by thomasyeh**

### CODE REVIEW

**Comment by thomasyeh** [comment]
Thanks 😀

**Comment by audreyt** [comment]
Thank _you_! :-) You're now a collaborator and if you have a CPAN ID please let me know — It'd be great to add you as a co-maintainer of this module.

**Comment by thomasyeh** [comment]
No CPAN ID at this moment. Will take a look into it. Thanks

**Comment by thomasyeh** [comment]
My PAUSE id: THOMASYEH. Please add me as co-maintainer of Parse::AFP.
Thanks 😀

**Comment by audreyt** [comment]
Done — Please make releases and commit to the repo — it's all yours!

**Pull request merged**
